### PR TITLE
Gdal 3.3.0

### PR DESCRIPTION
**Pull request by Kirill888**
- Based on Ubuntu 20.04
- Get rid of `:wheels` and local docker
- Support newest `pip` (none of the pre-compiled wheels stuff anymore)
- Upgrade GDAL and add LERC support
- Change image names to be `opendatacube/geobase-{builder|runner}:{latest|_gdal_version_}`

Preview readme changes here:
https://github.com/opendatacube/geobase/tree/gdal-3.3.0#readme

### CODE REVIEW

**Comment by woodcockr** [comment]
Have added this to the todo list for review

**Comment by Kirill888** [comment]
@woodcockr it's more of a "heads up" than obligation

**Comment by woodcockr** [comment]
Yeah, I get that but also good to have something fundamental tested by more than one organisation. We've been using most of this updated set up after our conversation back in Feb (Py 3.8, Ubuntu 20.04, no wheel image). All been good. The only fundamental issue we had was the lack of thread safety in PROJ6 causing issues. That is reportedly fixed in PROJ7 so that was on the cards next and I see you've got it in here already.
I should be able to get to this over the weekend and thus by early next week.

**Review by mmochan — APPROVED** [review]
LGTM!

**Pull request merged**
